import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
func = GPIO.gpio_function(01)
func = GPIO.gpio_function(2)
func = GPIO.gpio_function(3)
func = GPIO.gpio_function(4)
func = GPIO.gpio_function(5)
func = GPIO.gpio_function(6)
func = GPIO.gpio_function(7)
func = GPIO.gpio_function(8)
func = GPIO.gpio_function(9)
func = GPIO.gpio_function(10)
func = GPIO.gpio_function(11)
func = GPIO.gpio_function(12)
func = GPIO.gpio_function(13)
func = GPIO.gpio_function(14)
func = GPIO.gpio_function(15)
func = GPIO.gpio_function(16)
func = GPIO.gpio_function(17)
func = GPIO.gpio_function(18)
func = GPIO.gpio_function(19)
func = GPIO.gpio_function(20)
func = GPIO.gpio_function(21)
func = GPIO.gpio_function(22)
func = GPIO.gpio_function(23)
func = GPIO.gpio_function(24)
func = GPIO.gpio_function(25)
func = GPIO.gpio_function(26)
func = GPIO.gpio_function(27)
func = GPIO.gpio_function(28)
func = GPIO.gpio_function(29)
func = GPIO.gpio_function(30)
func = GPIO.gpio_function(31)
func = GPIO.gpio_function(32)
func = GPIO.gpio_function(33)
func = GPIO.gpio_function(34)
func = GPIO.gpio_function(35)
func = GPIO.gpio_function(36)
func = GPIO.gpio_function(37)
func = GPIO.gpio_function(38)
func = GPIO.gpio_function(39)
func = GPIO.gpio_function(40)


